name: GitHub Actions Demo
# 'run-name' is not a valid key - remove this line
on:
  push:
    branches:
      - main # specify the branch to trigger the workflow
  pull_request:
    branches:
      - main # specify the branch to trigger the workflow
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Unit Test
        run: npm run test:unit
      - name: E2E Test
        run: npm run test:e2e
      - name: Lint Code
        run: npm run lint
